site_name: 我的博客
site_url: https://Linsey0229.github.io/blog/
theme:
  name: material
  language: zh
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换至暗黑模式
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: 切换至明亮模式
nav:
  - 首页: index.md
  - 博客:
    - 《茉莉香片》书评: first-post.md
    - 《倾城之恋》书评: zhangailing.md
    - 《月华辉映之刻》鉴赏: moon.md