site_name: 我的博客
site_url: https://Linsey0229.github.io/blog/
theme:
  name: material
  language: zh
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换至暗黑模式
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: 切换至明亮模式
nav:
  - 首页: index.md
  - 博客:
    - 书评:
      - 茉莉香片: first-post.md
      - 倾城之恋: zhangailing.md
    - 游戏鉴赏:
      - 晚钟&终远: wan-zhong-zhong-yuan.md
      - 月华辉映之刻: moon.md
    - 同人文:
      - 【血相】血河与神相的十五年纠缠不休: shiwunian.md
      - 【血相】归途: guitu.md